FROM debian:trixie-slim

ENV LANG=C.UTF-8

RUN apt-get update -y && apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      # gnupg is required to install Node
      gnupg \
    ; \
    rm -rf /var/lib/apt/lists/*

ENV NODE_VERSION=22.22.1
ENV NODE_MAJOR=22
RUN set -eux; \
    ARCH="$(dpkg --print-architecture)"; \
    case "${ARCH}" in \
      amd64) NODE_ARCH='x64';; \
      arm64) NODE_ARCH='arm64';; \
      *) echo "Unsupported architecture: ${ARCH}"; exit 1;; \
    esac; \
    curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-${NODE_ARCH}.tar.gz" \
      | tar -xz -C /usr/local --strip-components=1 --no-same-owner; \
    corepack enable && \
    npm i -g npm && \
    # smoke tests
    node --version && npm --version && yarn --version

# Install google chrome
ARG GOOGLE_CHROME_VERSION=146.0.7680.80-1
RUN set -eux ; \

    apt-get update -y \
    && curl -Lo /tmp/google-chrome.deb "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${GOOGLE_CHROME_VERSION}_amd64.deb" \
    && apt install /tmp/google-chrome.deb -y --no-install-recommends \
    && rm /tmp/google-chrome.deb \
    && rm -rf /var/lib/apt/lists/*

ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV BROWSER_EXECUTABLE_PATH=/usr/bin/google-chrome
ENV PORT=9000

RUN set -eux ; \
  groupadd --gid 1000 node &&  \
  useradd --uid 1000 --gid node --shell /bin/bash --create-home node

ENV HOME=/home/node
ARG APP_HOME=/home/node/srv
WORKDIR $APP_HOME

RUN chown -R node:node $APP_HOME

USER node

# Uncomment when iterating locally to move faster:
#   COPY --chown=1000:1000 package.json ./
#   COPY --chown=1000:1000 package-lock.json ./
#   RUN npm install --omit=dev

COPY --chown=1000:1000 . ./

RUN npm install --omit=dev

EXPOSE $PORT
CMD ["node", "."]
