name: Lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
jobs:
  biome-check:
    name: Run biome checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Check
        run: npm run check
