name: Docker Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
jobs:
  test-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile.chrome -t urlapi .

      - name: Run tests inside Docker container
        run: |
          docker run --rm -t -e ALLOW_HTTP=true urlapi bash -c 'npm install && npm run test'

  test-chromium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile.chromium -t urlapi .

      - name: Run tests inside Docker container
        run: |
          docker run --rm -t -e ALLOW_HTTP=true urlapi bash -c 'npm install && npm run test'

  test-chromium-arm:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile.chromium -t urlapi .

      - name: Run tests inside Docker container
        run: |
          docker run --rm -t -e ALLOW_HTTP=true urlapi bash -c 'npm install && npm run test'
